version: "3.9"
services:
  sensors-debug:
    build:
      context: .
      dockerfile: Dockerfile.debug
    image: ${LOCAL_REGISTRY}:5002/sensors-debug:${TAG}
    ports:
      - 6502:6502
      - 6512:6512
      - 8080:8080

  sensors:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_LOGIN}/sensors:${TAG}
    ports:
      - 8080:8080
    logging:
      driver: "journald"
      options:
        tag: "compose"
